#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
# - resolves to 127.0.0.2 localhost
# - resolves to 8.8.8.8 facebook.com

# Update localhost resolution in /etc/hosts
sudo sed -i '/^127.0.0.1[[:space:]]\+localhost[[:space:]]*$/ s/127.0.0.1/127.0.0.2/' /etc/hosts

# Update facebook.com resolution in /etc/hosts
sudo sed -i '/^127.0.0.1[[:space:]]\+facebook\.com[[:space:]]*$/ s/127.0.0.1/8.8.8.8/' /etc/hosts

# Display all active IPv4 IPs
ip -4 address show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | sort -u
