#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.
# Display all active IPv4 IPs
ip -4 address show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | sort -u
